[workspace]
[package]
name = "core-create-artifact-revision"
version = "1.0.0"
edition = "2021"
publish = false
[[bin]]
name = "core-create-artifact-revision"
path = "src/main.rs"
[dependencies]
wasi-capability-runtime = { path = "../wasi-capability-runtime" }
[profile.release]
opt-level = "s"
lto = true
panic = "abort"
