#![no_std]
#![no_main]
const MAX_INPUT:usize=1_000_000; const MAX_OUTPUT:usize=2048; const MAX_SAMPLES:usize=48_000;
#[repr(C)]struct V{buffer:*const u8,length:usize} #[repr(C)]struct VM{buffer:*mut u8,length:usize}
#[link(wasm_import_module="wasi_snapshot_preview1")]unsafe extern "C"{fn fd_read(fd:u32,v:*const VM,count:usize,read:*mut usize)->u32;fn fd_write(fd:u32,v:*const V,count:usize,written:*mut usize)->u32;}
static mut I:[u8;MAX_INPUT]=[0;MAX_INPUT];static mut O:[u8;MAX_OUTPUT]=[0;MAX_OUTPUT];static mut S:[i16;MAX_SAMPLES]=[0;MAX_SAMPLES];
#[unsafe(no_mangle)]pub extern "C" fn _start(){unsafe{let ip=core::ptr::addr_of_mut!(I).cast::<u8>();let mut n=0;loop{let mut r=0;let v=VM{buffer:ip.add(n),length:MAX_INPUT-n};if fd_read(0,&v,1,&mut r)!=0||r==0{break}n+=r;if n==MAX_INPUT{break}}let s=core::slice::from_raw_parts_mut(core::ptr::addr_of_mut!(S).cast(),MAX_SAMPLES);let o=core::slice::from_raw_parts_mut(core::ptr::addr_of_mut!(O).cast(),MAX_OUTPUT);let w=run(core::slice::from_raw_parts(ip,n),o,s);let mut z=0;let v=V{buffer:core::ptr::addr_of!(O).cast(),length:w};let _=fd_write(1,&v,1,&mut z);}}
fn key(i:&[u8],k:&[u8])->Option<usize>{i.windows(k.len()).position(|w|w==k)}
fn int(i:&[u8],k:&[u8])->Option<i32>{let p=key(i,k)?;let c=i[p+k.len()..].iter().position(|b|*b==b':')?;let mut r=&i[p+k.len()+c+1..];while r.first().is_some_and(|b|b.is_ascii_whitespace()){r=&r[1..]}let mut n=0;let mut sign=1;if r.first()==Some(&b'-'){sign=-1;r=&r[1..]}let mut any=false;for b in r{if !b.is_ascii_digit(){break}n=n*10+(*b-b'0')as i32;any=true}if any{Some(n*sign)}else{None}}
fn samples(i:&[u8],s:&mut[i16])->Option<usize>{let p=key(i,b"\"samples\"")?;let mut r=&i[p..];r=&r[r.iter().position(|b|*b==b'[')?+1..];let mut n=0;loop{while r.first().is_some_and(|b|b.is_ascii_whitespace()||*b==b','){r=&r[1..]}if r.first()==Some(&b']'){return Some(n)}let mut sign=1;if r.first()==Some(&b'-'){sign=-1;r=&r[1..]}let mut v=0;let mut any=false;for b in r{if !b.is_ascii_digit(){break}v=v*10+(*b-b'0')as i32;any=true}if !any||n==s.len()||v*sign< -32768||v*sign>32767{return None} s[n]=(v*sign)as i16;n+=1;while r.first().is_some_and(|b|b.is_ascii_digit()){r=&r[1..]}if r.first()==Some(&b','){r=&r[1..]}}}
fn put(o:&mut[u8],at:&mut usize,b:&[u8]){if *at+b.len()<=o.len(){o[*at..*at+b.len()].copy_from_slice(b);*at+=b.len()}}
fn num(o:&mut[u8],at:&mut usize,mut n:i32){let mut b=[0;12];let mut c=0;if n==0{put(o,at,b"0");return}if n<0{put(o,at,b"-");n=-n}while n>0{b[c]=b'0'+(n%10)as u8;n/=10;c+=1}while c>0{c-=1;put(o,at,&b[c..c+1])}}
fn isqrt(n:i64)->i64{let(mut x,mut y)=(n,1i64);while y<x{let z=(x+n/x)/2;if z>=x{break}x=z;y=z}x}
fn run(i:&[u8],o:&mut[u8],s:&mut[i16])->usize{let Some(n)=samples(i,s)else{return err(o,b"invalid_samples")};let rate=int(i,b"\"sample_rate_hz\"").unwrap_or(0);if n==0||rate<1{return err(o,b"invalid_request")}let clip=int(i,b"\"clip_threshold\"").unwrap_or(32760);let quiet=int(i,b"\"quiet_rms_milli\"").unwrap_or(5);let ratio=int(i,b"\"clip_ratio_milli\"").unwrap_or(10);let mut peak=0i32;let mut sum=0i64;let(mut clips,mut crossings)=(0i32,0i32);for x in 0..n{let v=s[x]as i32;let a=if v<0{-v}else{v};if a>peak{peak=a}sum+=(v as i64)*(v as i64);if a>=clip{clips+=1}if x>0&&((s[x-1]<0&&s[x]>=0)||(s[x-1]>=0&&s[x]<0)){crossings+=1}}let rm=(isqrt(sum/n as i64)*1000/32768)as i32;let pm=peak*1000/32768;let cr=clips*1000/n as i32;let state:&[u8]=if cr>=ratio{b"clipped"}else if rm<quiet{b"quiet"}else{b"active"};let mut a=0;put(o,&mut a,b"{\"sample_count\":");num(o,&mut a,n as i32);put(o,&mut a,b",\"sample_rate_hz\":");num(o,&mut a,rate);put(o,&mut a,b",\"rms_milli\":");num(o,&mut a,rm);put(o,&mut a,b",\"peak_milli\":");num(o,&mut a,pm);put(o,&mut a,b",\"clipping_samples\":");num(o,&mut a,clips);put(o,&mut a,b",\"clip_ratio_milli\":");num(o,&mut a,cr);put(o,&mut a,b",\"zero_crossings\":");num(o,&mut a,crossings);put(o,&mut a,b",\"state\":\"");put(o,&mut a,state);put(o,&mut a,b"\"}");a}
fn err(o:&mut[u8],c:&[u8])->usize{let mut a=0;put(o,&mut a,b"{\"error\":\"");put(o,&mut a,c);put(o,&mut a,b"\"}");a}
#[panic_handler]fn panic(_: &core::panic::PanicInfo<'_>)->!{loop{}}
