//! Pure planning for a future audio transformation host operation.
#![cfg_attr(not(test), no_std)]
#![cfg_attr(not(test), no_main)]
extern crate alloc;
use alloc::string::String;
use wasi_capability_runtime::{object, Value};

fn positive(v: Option<&Value>) -> Option<i64> { let n=v?.as_f64()?; (n.is_finite()&&n>=1.0&&n<=i64::MAX as f64&&n==n as i64 as f64).then_some(n as i64) }
fn text<'a>(v: Option<&'a Value>, key:&str)->Option<&'a str>{v?.get(key)?.as_str().filter(|s|!s.is_empty())}
fn out(source:&str,rate:i64,channels:i64,encoding:&str,key:&str,result:&str)->Value { object(alloc::vec![("operation",Value::String(String::from(if result=="planned"{"transform"}else{""}))), ("source_artifact_ref",Value::String(String::from(source))), ("target_sample_rate_hz",Value::Number(rate as f64)), ("target_channel_count",Value::Number(channels as f64)), ("target_encoding",Value::String(String::from(encoding))), ("idempotency_key",Value::String(String::from(key))), ("result_class",Value::String(String::from(result)))]) }
fn plan(input:Value)->Value { let source=text(Some(&input),"source_artifact_ref").unwrap_or(""); let media=text(Some(&input),"source_media_type").unwrap_or(""); let key=text(Some(&input),"idempotency_key").unwrap_or(""); let rate=positive(input.get("target_sample_rate_hz")); let channels=positive(input.get("target_channel_count")); let encoding=text(Some(&input),"target_encoding").unwrap_or(""); if source.is_empty()||media.is_empty()||key.is_empty(){return out(source,0,0,"","","invalid_request")} if rate.is_none_or(|n|!(8000..=192000).contains(&n)){return out(source,0,0,"","","unsupported_sample_rate")} if channels.is_none_or(|n|!(1..=2).contains(&n)){return out(source,0,0,"","","unsupported_channel_count")} if !matches!(encoding,"pcm_s16le"|"pcm_s24le"|"pcm_f32le"){return out(source,0,0,"","","unsupported_encoding")} out(source,rate.unwrap_or_default(),channels.unwrap_or_default(),encoding,key,"planned") }
#[cfg(not(test))] #[unsafe(no_mangle)] pub extern "C" fn _start(){wasi_capability_runtime::run_capability(plan)}
#[cfg(test)] mod tests { use super::*; fn req(rate:Value,channels:Value,encoding:&str)->Value{object(alloc::vec![("source_artifact_ref",Value::String(String::from("asset:x"))),("source_media_type",Value::String(String::from("audio/flac"))),("target_sample_rate_hz",rate),("target_channel_count",channels),("target_encoding",Value::String(String::from(encoding))),("idempotency_key",Value::String(String::from("x")))])} fn result(v:&Value)->Option<&str>{v.get("result_class").and_then(Value::as_str)} #[test] fn plans_supported_formats(){for e in ["pcm_s16le","pcm_s24le","pcm_f32le"]{assert_eq!(result(&plan(req(Value::Number(48000.0),Value::Number(1.0),e))),Some("planned"))}} #[test] fn rejects_rates(){assert_eq!(result(&plan(req(Value::Number(4000.0),Value::Number(1.0),"pcm_s16le"))),Some("unsupported_sample_rate"))} #[test] fn rejects_channels(){assert_eq!(result(&plan(req(Value::Number(48000.0),Value::Number(3.0),"pcm_s16le"))),Some("unsupported_channel_count"))} #[test] fn rejects_encoding(){assert_eq!(result(&plan(req(Value::Number(48000.0),Value::Number(1.0),"mp3"))),Some("unsupported_encoding"))} #[test] fn rejects_invalid_numbers(){assert_eq!(positive(Some(&Value::Number(1.5))),None);assert_eq!(positive(Some(&Value::Number(0.0))),None)} }
